- name: Enable one-wire device tree overlay
  lineinfile: dest=/boot/config.txt line={{ item }}
  with_items:
    - dtoverlay=w1-gpio
  when: temperature_sensor.w1sensors is defined

- name: Enable i2c
  lineinfile: dest=/boot/config.txt line={{ item }}
  with_items:
    - dtparam=i2c_arm=on

- name: Enable i2c kernel module
  lineinfile:
    dest: /etc/modules
    line: i2c-dev

- name: Install needed packages
  apt:
    state: present
    name:
      - git
      - python-pip # so ansible's pip module can execute successfully
      - python3
      - python3-pip
      - python3-w1thermsensor
      - python3-smbus

- name: Fetch code from github
  become_user: pi
  git:
    repo: https://github.com/davea/temperature_sensor.git
    dest: /home/pi/temperature_sensor
  notify:
    - reload temperature_sensor

- name: Set up Python packages
  pip:
    executable: pip3
    requirements: /home/pi/temperature_sensor/requirements.txt

- name: Setup config dir
  file:
    path: /home/pi/.config/homesense
    state: directory
    owner: pi
    group: pi

- name: Install temperature sensor configuration
  template:
    src: temperature.ini.j2
    dest: /home/pi/.config/homesense/temperature.ini
    owner: pi
    group: pi
  notify:
    - reload temperature_sensor

- name: Create systemd service
  copy:
    src: temperature_sensor.service
    dest: /etc/systemd/system/temperature_sensor.service
    owner: root
    group: root

- name: Enable systemd service
  systemd:
    enabled: yes
    state: started
    name: temperature_sensor