- name: Enable one-wire device tree overlay
  lineinfile:
    dest: /boot/config.txt
    line: dtoverlay=w1-gpio

- name: Install needed packages
  apt: name={{ item }} state=latest
  with_items:
    - supervisor
    - python3
    - python3-pip
    - python3-w1thermsensor

- name: Fetch code from github
  become_user: pi
  git:
    repo: https://github.com/davea/rpi-mqtt-sensors.git
    dest: /home/pi/rpi-mqtt-sensors

- name: Set up Python packages
  pip:
    executable: pip3
    requirements: /home/pi/rpi-mqtt-sensors/requirements.txt

- name: Setup config dir
  file:
    path: /home/pi/.config/homesense
    state: directory
    owner: pi
    group: pi

- name: Install temperature sensor configuration
  template:
    src: temperature.ini.j2
    dest: /home/pi/.config/homesense/temperature.ini
    owner: pi
    group: pi

- name: Setup supervisor task
  copy:
    src: supervisor.conf
    dest: /etc/supervisor/conf.d/temperature_sensor.conf
    owner: root
    group: root
  notify:
    - reload supervisor

- name: Disable SSH password logins
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: PasswordAuthentication no
